=== pietrorisipr-2025/CoreLang-5/Toolkit/CL5_1_Performance_Pack_v0_1/schemas/manifest_v1_1.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CoreLang Manifest v1.1",
  "type": "object",
  "required": [
    "version",
    "release_id",
    "profiles",
    "compression_policy",
    "files"
  ],
  "properties": {
    "version": {
      "type": "string",
      "enum": [
        "1.1"
      ]
    },
    "release_id": {
      "type": "string"
    },
    "profiles": {
      "type": "array"
    },
    "compression_policy": {
      "type": "object"
    },
    "files": {
      "type": "array"
    },
    "hints": {
      "type": "object"
    }
  }
}

=== pietrorisipr-2025/CoreLang-5/Toolkit/CL5_1_Performance_Pack_v0_1/manifest/manifest_v1_1_example.json
{
  "version": "1.1",
  "release_id": "cl5_r23_pp_v0_1",
  "profiles": [
    {
      "name": "rtt_10",
      "rtt_ms": 10,
      "recommendations": {
        "shard_kib": 512,
        "concurrency_k": 32,
        "http3_streams": 32,
        "energy_mode": "turbo"
      }
    },
    {
      "name": "rtt_35",
      "rtt_ms": 35,
      "recommendations": {
        "shard_kib": 512,
        "concurrency_k": 48,
        "http3_streams": 48,
        "energy_mode": "turbo"
      }
    },
    {
      "name": "rtt_100",
      "rtt_ms": 100,
      "recommendations": {
        "shard_kib": 256,
        "concurrency_k": 64,
        "http3_streams": 64,
        "energy_mode": "turbo"
      }
    },
    {
      "name": "rtt_250",
      "rtt_ms": 250,
      "recommendations": {
        "shard_kib": 256,
        "concurrency_k": 32,
        "http3_streams": 32,
        "energy_mode": "eco"
      }
    }
  ],
  "compression_policy": {
    "zstd_level": 9,
    "rules": [
      {
        "ext": ".json",
        "mode": "on"
      },
      {
        "ext": ".csv",
        "mode": "on"
      },
      {
        "ext": ".zip",
        "mode": "off"
      },
      {
        "ext": ".cl5b",
        "mode": "dict_light"
      }
    ]
  },
  "files": [
    {
      "path": "blocks/CoreLang5_Block1_Logic_and_ControlFlow.zip",
      "bytes": 1234567,
      "sha256": "d34db33f..."
    }
  ],
  "hints": {
    "priority_pareto": [
      "Block10",
      "Block4",
      "Block1"
    ],
    "quic_streams_hint": 48
  }
}

=== pietrorisipr-2025/CoreLang-5/Toolkit/CL5_2_Reliability_Observability_Pack_v0_1/manifest/manifest_v1_1_http3_hints.json
{
  "version": "1.1",
  "release_id": "cl5_r23_pp_v0_2",
  "profiles": [
    {
      "name": "rtt_10",
      "rtt_ms": 10,
      "recommendations": {
        "shard_kib": 512,
        "concurrency_k": 32,
        "http3_streams": 32,
        "energy_mode": "turbo"
      }
    },
    {
      "name": "rtt_100",
      "rtt_ms": 100,
      "recommendations": {
        "shard_kib": 256,
        "concurrency_k": 64,
        "http3_streams": 64,
        "energy_mode": "turbo"
      }
    },
    {
      "name": "rtt_250",
      "rtt_ms": 250,
      "recommendations": {
        "shard_kib": 256,
        "concurrency_k": 32,
        "http3_streams": 32,
        "energy_mode": "eco"
      }
    }
  ],
  "compression_policy": {
    "zstd_level": 9,
    "rules": [
      {
        "ext": ".json",
        "mode": "on"
      },
      {
        "ext": ".csv",
        "mode": "on"
      },
      {
        "ext": ".zip",
        "mode": "off"
      },
      {
        "ext": ".cl5b",
        "mode": "dict_light"
      }
    ]
  },
  "hints": {
    "quic_streams_hint": 64,
    "priority_pareto": [
      "Block10",
      "Block4",
      "Block1"
    ]
  },
  "files": []
}
